kmeans-serial:
	g++ -O3 -Wall -Werror -g -o kmeans-serial kmeans-serial.cpp

# prime_static:
# 	g++ -O3 -ltbb -lpthread -Wall -Werror -g -o prime_static prime_static.cpp

clean_kmeans-serial:
	rm -f kmeans-serial

clean:
	rm -f kmeans-serial