prime_tbb:
	g++ -O3 -ltbb -lpthread -Wall -Werror -g -o prime_tbb prime_tbb.cpp

prime_static:
	g++ -O3 -ltbb -lpthread -Wall -Werror -g -o prime_static prime_static.cpp

prime_dynamic:
	g++ -O3 -ltbb -lpthread -Wall -Werror -g -o prime_dynamic prime_dynamic.cpp

clean_prime_tbb:
	rm -f prime_tbb

clean_prime_static:
	rm -f prime_static

clean_prime_dynamic:
	rm -f prime_dynamic

clean:
	rm -f prime_tbb prime_static prime_dynamic